### ISSUE TITLE
Add MSI smoke tests

### ISSUE THREAD

**Issue by pjanotti** [open-telemetry/opentelemetry-collector-releases#576]
Windows MSI installers were recently added, but, there are no smoke tests for them and MSIs have enough capabilities and use cases  to deserve tests.

Related conversation at https://github.com/open-telemetry/opentelemetry-collector-releases/issues/157#issuecomment-2159297330

cc @briantist

**Comment by pjanotti** [comment]
I am experiencing a lot of instability running MSI tests on GH Windows runners. Two main categories of issues:

1. It seems that the test matrix cause some kind of noise neighbor problem, setting it to no concurrence reduce the errors, but, still high error rate with golang tests.
2. This is also much less frequent when I use PowerShell scripts instead of golang tests, but, I get many "The operation was canceled" errors on the runner.

```
Error: The operation was canceled.
##[debug]System.OperationCanceledException: The operation was canceled.
##[debug]   at System.Threading.CancellationToken.ThrowOperationCanceledException()
##[debug]   at GitHub.Runner.Sdk.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Common.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Channel`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.DefaultStepHost.ExecuteAsync(IExecutionContext context, String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, String standardInInput, CancellationToken cancellationToken)
##[debug]   at GitHub.Runner.Worker.Handlers.ScriptHandler.RunAsync(ActionRunStage stage)
##[debug]   at GitHub.Runner.Worker.ActionRunner.RunAsync()
##[debug]   at GitHub.Runner.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
```

@briantist have you had similar issues in your MSI tests?

**Comment by pjanotti** [comment]
A larger instance solves problem 2 above and precludes the need to run the tests in a job matrix.
